## **Etapa 1: Obtencion de datos**

En esta práctica obtendrás los datos para predecir si un falcon 9 aterizará con éxito o no. Los datos serán recogidos mediante la API de SpaceX y nos aseguraremos de que siguen un formato adecuado para las fases siguientes. El siguiente es un ejemplo de un aterrizaje exitoso:

![](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DS0701EN-SkillsNetwork/lab_v2/images/landing\_1.gif)

Aquí puedes ver varios ejemplos de aterrizajes fallidos:

![](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DS0701EN-SkillsNetwork/lab_v2/images/crash.gif)

La gran mayoría de aterrizajes fallidos son intencionados para la realización de diversos controles. Estos aterrizajes se llevan a cabo la mayoria en el oceano, veremos estadísticas al respecto.

## Objetivos


En esta práctica realizaras una GET request a la API de SpaceX. Tambien realizarás cierto data wrangling básico y limpieza de datos.

***

## Importación de librerias.

Nos importamos las siguientes librerías necesarias para el desarrollo de la práctica.

In [17]:
import requests
import pandas as pd
import numpy as np
import datetime

pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
#Las opciones anteriores aseguran que pandas muestre el df completo en jupyternotebooks

Realicemos ahora una petición GET a la API de SpaceX. La URL es la siguiente.

In [23]:
spacex_url="https://api.spacexdata.com/v4/launches/past"

* Usando la librería requests usa el método GET y pasale como argumento URL anterior, guardala en una variable `response`  y realiza el print de `response.content`

In [ ]:
import re
#INSERTA AQUÍ TU CÓDIGO
#requests.TIPODEPETICIÓN(URL)
response= requests.get(spacex_url)
print(response.content)

Si la petición ha sido realizada correctamente el resultado del print debería ser similar al siguiente:


```
b'[{"fairings":{"reused":false,"recovery_attempt":false,"recovered":false, ...
```
(Recomendamos cerrar el resultado del print después de revisarlo para que google collab no sufra.)

Nuestra variable `response` contiene una grandísima cantidad de información sobre los SpaceX pero vamos a intentar formatearla para poder ver de que se trata exactamente y que nos interesa.

### Parte 1: Obtén los datos mediante peticiones GET y crea un dataframe

Hemos observado que la variable `response` tiene forma de diccionario (como la mayoría de respuestas a peticiones GET). Una forma efectiva de formatear dichos datos es transformarlos en un JSON y posteriormente en un dataframe de python:

In [27]:
data=response.json()
data=pd.json_normalize(data)

*Utilizando el dataframe anterior muestra las 5 primeras filas*

In [ ]:
#INSERTA AQUÍ TU CÓDIGO
data[0:5]

Observemos que la mayoría de datos interesantes no se muestran de forma explícita sino que son IDs. Estos IDs nos permiten obtener mas información haciendo pediciones GET a diferentes endpoints de la API.
Para mas infrmación: https://docs.spacexdata.com/

Revisando la documentación de la API nos hemos dado cuenta de que no son necesarias todas las columnas, por lo que vamos a reducir nuestro dataframe a lo crucial:

In [32]:
#Reescribe el dataframe para quedarnos solo con las columnas'rocket', 'payloads','success', 'launchpad', 'cores', 'flight_number', 'date_utc'
#INSERTA AQUÍ TU CÓDIGO:
data =data[['rocket', 'payloads','success', 'launchpad', 'cores', 'flight_number', 'date_utc']]

In [33]:
# Algunos cohetes tienen mas de una carga 'payload' o 'core'. 
# Estos datos nos darán problemas en un futuro, entonces nos limitearemos a aquellos que solamente tienen un core o una carga (payload):
data = data[data['cores'].map(len)==1]
#INSERTA AQUI TU CÓDIGO para payloads
data = data[data['payloads'].map(len)==1]

In [34]:
# Otro problema que tenemos es que ahora tenemos listas de longitud 1. 
# Las listas de python no son especialmente compatibles con SQL por lo que lo solucionaremos sacando el valor de la lista:
data['cores'] = data['cores'].map(lambda x : x[0])
#INSERTA AQUI TU CÓDIGO para hacer lo mismo con la columna payloads
data['payloads'] = data['payloads'].map(lambda x : x[0])

In [35]:
# El formato de la fecha no es especialmete cómodo por lo que lo formatearemos:
data['date'] = pd.to_datetime(data['date_utc']).dt.date

No se te olvide ejecutar la celda anterior (1 sola vez)

In [39]:
data.head()

,rocket,payloads,success,launchpad,cores,flight_number,date_utc,date
0,5e9d0d95eda69955f709d1eb,5eb0e4b5b6c3bb0006eeb1e1,False,5e9e4502f5090995de566f86,"{'core': '5e9e289df35918033d3b2623', 'flight': 1, 'gridfins': False, 'legs': False, 'reused': False, 'landing_attempt': False, 'landing_success': None, 'landing_type': None, 'landpad': None}",1,2006-03-24T22:30:00.000Z,2006-03-24
1,5e9d0d95eda69955f709d1eb,5eb0e4b6b6c3bb0006eeb1e2,False,5e9e4502f5090995de566f86,"{'core': '5e9e289ef35918416a3b2624', 'flight': 1, 'gridfins': False, 'legs': False, 'reused': False, 'landing_attempt': False, 'landing_success': None, 'landing_type': None, 'landpad': None}",2,2007-03-21T01:10:00.000Z,2007-03-21
3,5e9d0d95eda69955f709d1eb,5eb0e4b7b6c3bb0006eeb1e5,True,5e9e4502f5090995de566f86,"{'core': '5e9e289ef3591855dc3b2626', 'flight': 1, 'gridfins': False, 'legs': False, 'reused': False, 'landing_attempt': False, 'landing_success': None, 'landing_type': None, 'landpad': None}",4,2008-09-28T23:15:00.000Z,2008-09-28
4,5e9d0d95eda69955f709d1eb,5eb0e4b7b6c3bb0006eeb1e6,True,5e9e4502f5090995de566f86,"{'core': '5e9e289ef359184f103b2627', 'flight': 1, 'gridfins': False, 'legs': False, 'reused': False, 'landing_attempt': False, 'landing_success': None, 'landing_type': None, 'landpad': None}",5,2009-07-13T03:35:00.000Z,2009-07-13
5,5e9d0d95eda69973a809d1ec,5eb0e4b7b6c3bb0006eeb1e7,True,5e9e4501f509094ba4566f84,"{'core': '5e9e289ef359185f2b3b2628', 'flight': 1, 'gridfins': False, 'legs': False, 'reused': False, 'landing_attempt': False, 'landing_success': None, 'landing_type': None, 'landpad': None}",6,2010-06-04T18:45:00.000Z,2010-06-04

-------------------

Si revisamos `rocket, payload,launchpad y cores` son IDs, estos IDs nos permiten hacer peticiones a diferetes endpoints y obtener más información. La información para cada variable se encuentra en los siguientes links:

*   Para <code>rocket</code> https://github.com/r-spacex/SpaceX-API/blob/master/docs/rockets/v4/one.md . De aquí nos quedaremos la versión del cohete propulsor.

*   Para <code>payload</code> https://github.com/r-spacex/SpaceX-API/blob/master/docs/payloads/v4/one.md . De aquí guardaremos la carga, la masa de esta carga, la orbita a la que fue enviada y el cliente.

*   Para <code>launchpad</code> https://github.com/r-spacex/SpaceX-API/blob/master/docs/launchpads/v4/one.md . Guardamos la latitud, longitud y nombre de las diferentes plataformas de lanzamiento.

*   Para <code>cores</code> https://github.com/r-spacex/SpaceX-API/blob/master/docs/cores/v4/one.md . Gaurdamos diferentes variables del nucleo.

Los datos serán guardados en listas y estas listas las utilizaremos para crear una nuevo dataframe con todos los datos:

In [36]:
#Para rocket
BoosterVersion = [] 

#Para paylaod
PayloadMass = []
Payload = []
Orbit = []
Customers= []

#Para launchpad
LaunchSite = []
Longitude = []
Latitude = []

#Para core
Outcome = []
Flights = []
GridFins = []
Reused = []
Legs = []
LandingPad = []
Block = []
Mission_Outcome = []
ReusedCount = []
Serial = []

Para completar las listas anteriores nos definiremos una lista de funciones para facilitar la obtención de los datos.

Empecemos con los cohetes:

In [74]:
# DEFINICIÓN FUNCIÓN 1
def getBoosterVersion(data): #Definimos la función
    for x in data['rocket']: #Iteramos por cada fila de la columna rocket
       if x: #Comprobamos que no este vacía
        response = requests.get("https://api.spacexdata.com/v4/rockets/"+str(x)) #Realizamos la petición GET (Aplicamos str() para poder concatenar)
        response = response.json() #Transformamos la respuesta en un diccionario.
        BoosterVersion.append(response['name']) #Añadimos a BoosterVersion el valor con key 'name'

De <code>launchpad</code> nos gustaría quedarnos con la longitud, la latitud y el nombre de la plataforma

In [98]:
# DEFINICIÓN FUNCIÓN 2
#INSERTA AQUI TU CÓDIGO
def getLaunchSite(data):
  for x in data ["launchpad"]:
    if x:
      response=requests.get("https://api.spacexdata.com/v4/launchpads/"+(x))
      response= response.json()
      LaunchSite.append(response["name"])
      Longitude.append(response["longitude"])
      Latitude.append(response["latitude"])
      
#Definimos la función getLaunchSite que recibe con argumento data
#Iteramos por cada fila de la columna launchpad
#Comprobamos que no este vacía
#Realizamos la petición GET (Aplicamos str() para poder concatenar)
#Transformamos la respuesta en un diccionario.
#Añadimos a Longitude el valor con key 'longitude'
#Añadimos a Latitude el valor con key 'latitude'
#Añadimos a LaunchSite el valor con key 'name'

De <code>payload</code> nos gustaría obtener la carga, el peso de la carga, el cliente y la órbita a la que fué enviada.

In [94]:
# DEFINICIÓN FUNCIÓN 3
#INSERTA AQUI TU CÓDIGO
def getPayloadData(data):
  for x in data ["payloads"]:
    if x:
      response=requests.get("https://api.spacexdata.com/v4/payloads/"+(x))
      response= response.json()
      Payload.append(response["name"])
      PayloadMass.append(response["mass_kg"])
      Orbit.append(response["orbit"])
      Customers.append(response["customers"])

#Definimos la función getPayloadData
#Iteramos por cada fila de la columna payloads
#Comprobamos que no este vacía
#Realizamos la petición GET (Aplicamos str() para poder concatenar)
#Transformamos la respuesta en un diccionario.
#Añadimos a Payload el valor con key 'name'
#Añadimos a Customers el valor con key 'customers'
#Añadimos a PayloadMass el valor con key 'mass_kg'
#Añadimos a Orbit el valor con key 'orbit'

La función para completar los datos de `core` tiene una complicación extra por lo que la damos hecha:

In [71]:
# DEFINICIÓN FUNCIÓN 4
def getCoreData(data):
    for core in data['cores']:
            if core['core'] != None:
                response = requests.get("https://api.spacexdata.com/v4/cores/"+core['core']).json()
                Block.append(response['block'])
                ReusedCount.append(response['reuse_count'])
                Serial.append(response['serial'])
            else:
                Block.append(None)
                ReusedCount.append(None)
                Serial.append(None)
            Outcome.append(str(core['landing_success'])+' '+str(core['landing_type']))
            Flights.append(core['flight'])
            GridFins.append(core['gridfins'])
            Reused.append(core['reused'])
            Legs.append(core['legs'])
            LandingPad.append(core['landpad'])


Las funciones anteriores rellenan las listas vacías, veamoslo en práctica. *Revisa que la lista BoosterVersion esta vacía*

In [60]:
#INSERTA AQUI TU CÓDIGO
print(BoosterVersion)

[]

*Llama ahora la función `getBoosterVersion`.* (No devuelve nada así que no hace falta asignarle una variable. Solo instanciamos la funcion.)

In [65]:
# LLAMADA A FUNCIÓN 1
#INSERTA AQUI TU CÓDIGO
getBoosterVersion(data)

*Muestra los primeros 5 valores de la lista `BoosterVersion`*

In [66]:
#INSERTA AQUI TU CÓDIGO
BoosterVersion[0:5]

['Falcon 1', 'Falcon 1', 'Falcon 1', 'Falcon 1', 'Falcon 9']

*Aplica el resto de funciones:*
(No devuelven nada así que no hace falta asignarles una variable. Solo instanciamos a las funciones.)

In [99]:
# LLAMADA A FUNCIÓN 2
#INSERTA AQUI TU CÓDIGO
getLaunchSite(data)

In [97]:
# LLAMADA A FUNCIÓN 3
#INSERTA AQUI TU CÓDIGO
getPayloadData(data)

In [85]:
# LLAMADA A FUNCIÓN 4
#INSERTA AQUI TU CÓDIGO
getCoreData(data)

Finalmente creamos un dataframe desde las listas anteriores. Primero convirtámolos en un diccionario:

In [123]:
launch_dict = {'FlightNumber': list(data['flight_number']),
'Date': list(data['date']),
'BoosterVersion':BoosterVersion,
'PayloadMass':PayloadMass,
'Payload':Payload,
'Orbit':Orbit,
'LaunchSite':LaunchSite,
'LandingOutcome':Outcome,
'Flights':Flights,
'GridFins':GridFins,
'Reused':Reused,
'Legs':Legs,
'LandingPad':LandingPad,
'Block':Block,
'Customers': Customers,
'Mission_Outcome':list(data['success']),
'ReusedCount':ReusedCount,
'Serial':Serial,
'Longitude': Longitude,
'Latitude': Latitude}

Y ahora crea un dataframe de Pandas desde el diccionario. Llámalo `launch_data`

In [127]:
#INSERTA AQUI TU CÓDIGO
launch_data =pd.DataFrame(launch_dict)

Finalmente, muestra las primeras 5 filas del dataframe.

In [130]:
#INSERTA AQUI TU CÓDIGO
launch_data.head()

,FlightNumber,Date,BoosterVersion,PayloadMass,Payload,Orbit,LaunchSite,LandingOutcome,Flights,GridFins,Reused,Legs,LandingPad,Block,Customers,Mission_Outcome,ReusedCount,Serial,Longitude,Latitude
0,1,2006-03-24,Falcon 1,20.0,FalconSAT-2,LEO,Kwajalein Atoll,None None,1,False,False,False,None,NaN,[DARPA],False,0,Merlin1A,167.743129,9.047721
1,2,2007-03-21,Falcon 1,NaN,DemoSAT,LEO,Kwajalein Atoll,None None,1,False,False,False,None,NaN,[DARPA],False,0,Merlin2A,167.743129,9.047721
2,4,2008-09-28,Falcon 1,165.0,RatSat,LEO,Kwajalein Atoll,None None,1,False,False,False,None,NaN,[SpaceX],True,0,Merlin2C,167.743129,9.047721
3,5,2009-07-13,Falcon 1,200.0,RazakSAT,LEO,Kwajalein Atoll,None None,1,False,False,False,None,NaN,[ATSB],True,0,Merlin3C,167.743129,9.047721
4,6,2010-06-04,Falcon 9,NaN,Dragon Qualification Unit,LEO,CCSFS SLC 40,None None,1,False,False,False,None,1.0,[SpaceX],True,0,B0003,-80.577366,28.561857

### Parte 2: Filtra el dataframe para que solo incluya los lanzamientos de falcon 9


El falcon 9 es una versión considerablemente más nueva y efectiva que el faclon 1. Dado que nos interesan los datos recientes y a futuro vamos a *eliminar los lanzamientos de `Falcon 1` del fataframe launch_data y llama al nuevo dataframe `data_falcon9`. Muestra las primeras 5 filas.*

In [135]:
# INSERTA AQUÍ TU CÓDIGO
launch_data["BoosterVersion"] != "Falcon 1"
data_falcon9 =launch_data 
data_falcon9.head

<bound method NDFrame.head of      FlightNumber        Date BoosterVersion  PayloadMass  \
0               1  2006-03-24       Falcon 1         20.0
1               2  2007-03-21       Falcon 1          NaN
2               4  2008-09-28       Falcon 1        165.0
3               5  2009-07-13       Falcon 1        200.0
4               6  2010-06-04       Falcon 9          NaN
..            ...         ...            ...          ...
167           181  2022-08-28       Falcon 9      13260.0
168           182  2022-08-31       Falcon 9      13260.0
169           185  2022-09-17       Falcon 9      13260.0
170           186  2022-09-24       Falcon 9      13260.0
171           187  2022-10-05       Falcon 9          NaN

                       Payload Orbit       LaunchSite LandingOutcome  Flights  \
0                  FalconSAT-2   LEO  Kwajalein Atoll      None None        1
1                      DemoSAT   LEO  Kwajalein Atoll      None None        1
2                       RatSat   LEO  Kwajalein Atoll      None None        1
3                     RazakSAT   LEO  Kwajalein Atoll      None None        1
4    Dragon Qualification Unit   LEO     CCSFS SLC 40      None None        1
..                         ...   ...              ...            ...      ...
167       Starlink 4-23 (v1.5)  VLEO       KSC LC 39A      True ASDS        2
168        Starlink 3-4 (v1.5)  VLEO      VAFB SLC 4E      True ASDS        7
169       Starlink 4-34 (v1.5)  VLEO     CCSFS SLC 40      True ASDS        6
170       Starlink 4-35 (v1.5)  VLEO     CCSFS SLC 40      True ASDS        4
171                     Crew-5   ISS       KSC LC 39A      True ASDS        1

     GridFins  Reused   Legs                LandingPad  Block  \
0       False   False  False                      None    NaN
1       False   False  False                      None    NaN
2       False   False  False                      None    NaN
3       False   False  False                      None    NaN
4       False   False  False                      None    1.0
..        ...     ...    ...                       ...    ...
167      True    True   True  5e9e3033383ecb075134e7cd    5.0
168      True    True   True  5e9e3032383ecb6bb234e7ca    5.0
169      True    True   True  5e9e3033383ecbb9e534e7cc    5.0
170      True    True   True  5e9e3033383ecbb9e534e7cc    5.0
171      True   False   True  5e9e3033383ecbb9e534e7cc    5.0

           Customers Mission_Outcome  ReusedCount    Serial   Longitude  \
0            [DARPA]           False            0  Merlin1A  167.743129
1            [DARPA]           False            0  Merlin2A  167.743129
2           [SpaceX]            True            0  Merlin2C  167.743129
3             [ATSB]            True            0  Merlin3C  167.743129
4           [SpaceX]            True            0     B0003  -80.577366
..               ...             ...          ...       ...         ...
167         [SpaceX]            True            1     B1069  -80.603956
168         [SpaceX]            True            6     B1063 -120.610829
169         [SpaceX]            True            5     B1067  -80.577366
170         [SpaceX]            True            0     B1072  -80.577366
171  [NASA (CCtCap)]            True            0     B1077  -80.603956

      Latitude
0     9.047721
1     9.047721
2     9.047721
3     9.047721
4    28.561857
..         ...
167  28.608058
168  34.632093
169  28.561857
170  28.561857
171  28.608058

[172 rows x 20 columns]>

Ahora que hemos eliminado los lanzamientos de Falcon 1 la columna FlightNumber está desajustada. Vamos a volver a ordenarla:

In [136]:
data_falcon9.FlightNumber = list(range(1, data_falcon9.shape[0]+1))
data_falcon9.head()

,FlightNumber,Date,BoosterVersion,PayloadMass,Payload,Orbit,LaunchSite,LandingOutcome,Flights,GridFins,Reused,Legs,LandingPad,Block,Customers,Mission_Outcome,ReusedCount,Serial,Longitude,Latitude
0,1,2006-03-24,Falcon 1,20.0,FalconSAT-2,LEO,Kwajalein Atoll,None None,1,False,False,False,None,NaN,[DARPA],False,0,Merlin1A,167.743129,9.047721
1,2,2007-03-21,Falcon 1,NaN,DemoSAT,LEO,Kwajalein Atoll,None None,1,False,False,False,None,NaN,[DARPA],False,0,Merlin2A,167.743129,9.047721
2,3,2008-09-28,Falcon 1,165.0,RatSat,LEO,Kwajalein Atoll,None None,1,False,False,False,None,NaN,[SpaceX],True,0,Merlin2C,167.743129,9.047721
3,4,2009-07-13,Falcon 1,200.0,RazakSAT,LEO,Kwajalein Atoll,None None,1,False,False,False,None,NaN,[ATSB],True,0,Merlin3C,167.743129,9.047721
4,5,2010-06-04,Falcon 9,NaN,Dragon Qualification Unit,LEO,CCSFS SLC 40,None None,1,False,False,False,None,1.0,[SpaceX],True,0,B0003,-80.577366,28.561857

### Parte 3: Ajustes finales

Debajo podemos observar que nos faltan ciertos valores.

In [137]:
data_falcon9.isnull().sum()

FlightNumber        0
Date                0
BoosterVersion      0
PayloadMass        23
Payload             0
Orbit               1
LaunchSite          0
LandingOutcome      0
Flights             0
GridFins            0
Reused              0
Legs                0
LandingPad         30
Block               4
Customers           0
Mission_Outcome     1
ReusedCount         0
Serial              0
Longitude           0
Latitude            0
dtype: int64

* Lo óptimo sería no tener celdas vacías por lo que vamos a ver que podemos hacer para solucionar esta situación.
La columna <code>LandingPad</code> tiene valores `None`en los casos donde el cohete no tuvo intención de aterrizar por lo que no tenía ningún LandingPad asignado. 

* Por otro lado, los valores innexistentes de `PayloadMass` si se pueden completar. *En este caso utilizaras la función `.mean()` para calcular la media y `.replace()` para reemplzar los valores `np.nan`.*

In [138]:
# INSERTA AQUI TU CÓDIGO
media = data_falcon9["PayloadMass"].mean()
nuevos_valores =data_falcon9["PayloadMass"].replace(np.nan,media)
data_falcon9 ["PayloadMass"] = nuevos_valores
data_falcon9.isnull().sum()

FlightNumber        0
Date                0
BoosterVersion      0
PayloadMass         0
Payload             0
Orbit               1
LaunchSite          0
LandingOutcome      0
Flights             0
GridFins            0
Reused              0
Legs                0
LandingPad         30
Block               4
Customers           0
Mission_Outcome     1
ReusedCount         0
Serial              0
Longitude           0
Latitude            0
dtype: int64

El número de celdas vacías en la columna <code>PayLoadMass</code> debería cambiar a 0.

Por último tenemos que la columna `Customers` es una lista, y como hemos comentado previamente, no se llevan especialmente bien con SQL. 
*Transforma esta lista en una string aplicando `.map(lambda x : ','.join(x))` a la columna y guardalo en la misma columna.*

In [139]:
#INSERTA AQUÍ TU CÓDIGO
data_falcon9["Customers"].map(lambda x : ','.join(x))
data_falcon9["Customers"]

0              [DARPA]
1              [DARPA]
2             [SpaceX]
3               [ATSB]
4             [SpaceX]
            ...
167           [SpaceX]
168           [SpaceX]
169           [SpaceX]
170           [SpaceX]
171    [NASA (CCtCap)]
Name: Customers, Length: 172, dtype: object

*Ahora exporta el dataset en formato `.csv`  con `index=False` y llámalo `dataset_part_1.csv`. Descarga el archivo porque será necesario en la siguiente práctica.*

In [141]:
#INSERTA AQUÍ TU CÓDIGO
data_falcon9.to_csv("dataset_part_1",index=False)